controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

anime_view:
    path: '/anime/{id}'
    controller: 'App\Controller\AnimeViewController::view'
    methods: ['GET']
